resources:
  - name: same_gitRepo2
    type: GitRepo
    configuration:
      gitProvider: testInt
      path: akhilesh073/TestYmlPipeline
      branches:
        include: master

  - name: gitRepo_githubhttp
    type: GitRepo
    configuration:
      gitProvider: testInt
      path: akhilesh073/xray-pipelines-repo
      cloneProtocol: https
      branches:
        include: main

  - name: versionbag1
    type: PropertyBag
    configuration:
      version: '1.0.0'

  - name: branchbag1
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag1
    type: PropertyBag
    configuration:
      pipeline_v: ''

pipelines:
  - name: simplePipelines1
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          #           timeoutSeconds: 60
          inputResources:
            - name: same_gitRepo2
            - name: gitRepo_githubhttp
          outputResources:
            - name: versionbag1
            - name: branchbag1
            - name: pipelineVBag1
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - echo "aaa bbb ccc"
            - write_output versionbag1 "version=$run_id"
            - write_output branchbag1 "branch_name=$run_id"
            - write_output pipelineVBag1 "pipeline_v=$run_id"

      - name: simpleBash2
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash1
          inputResources:
            - name: same_gitRepo2
            - name: gitRepo_githubhttp
        execution:
          onExecute:
            - printenv
      - name: simpleBash_abc
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash1
          inputResources:
            - name: same_gitRepo2
            - name: gitRepo_githubhttp
        execution:
          onExecute:
            - printenv
      - name: simpleBash4
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash1
            - name: simpleBash2
          inputResources:
            - name: versionbag1
            - name: gitRepo_githubhttp
            - name: same_gitRepo2
        execution:
          onExecute:
            - printenv
